Description:
  Mike Ajala / Powerjamb
  This resource deploys a VPC on AWS
Resources:
  UdacityVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: True