Description:
  Mike Ajala / Powerjamb
  This resource deploys a VPC on AWS
Resources:
  UdacityVPC:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: String
      EnableDnsHostnames: Boolean
      EnableDnsSupport: Boolean
      InstanceTenancy: String
      Tags: 
        - Tag