Description:
  Michael makes a submission for DevOps Project 2

Parameters:
# whatever you consider a changing value, put it as a parameter instead of hard-coding it into your script

  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

Resources:

  VPC: 
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags: 
        - Key: Name 
          Value: !Ref EnvironmentName
  
Outputs: 
  #Bonus points for useful outputs!